// app/layout.tsx or app/layout.ts
import "./globals.css";
import { GeistSans, GeistMono } from "geist/font"; // ensure you're using the right font import
import type { Metadata } from "next";
import ReactQueryProvider from "./utilis/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body className="font-sans"> {/* Add class for base font */}
        <ReactQueryProvider>
          {children}
          
          </ReactQueryProvider>
      </body>
    </html>
  );
}
